apiVersion: v2
name: RepoUniqueNormalisedIdentifier
description: A Helm chart for a Pellerex Managed App Service (React/Vite on nginx) - RepoUniqueNormalisedIdentifier
type: application
version: 0.1.0
appVersion: "1.0.0"
