name: CD
on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  qualityassurance:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: pellerex-platform/workflows/.github/workflows/cd.yaml@v1
    with:
      project_name: Pellerex.Ecosystem.ManagedApp.RepoUniqueNormalisedIdentifier
      helm_release_name: RepoUniqueIdentifier
      docker_repository: pellerex/RepoUniqueNormalisedIdentifier
      kubernetes_namespace: <qualityassurance-namespace>
      target_environment: qualityassurance
    secrets: inherit

  staging:
    needs: qualityassurance
    uses: pellerex-platform/workflows/.github/workflows/cd.yaml@v1
    with:
      project_name: Pellerex.Ecosystem.ManagedApp.RepoUniqueNormalisedIdentifier
      helm_release_name: RepoUniqueIdentifier
      docker_repository: pellerex/RepoUniqueNormalisedIdentifier
      kubernetes_namespace: <staging-namespace>
      target_environment: staging
    secrets: inherit

  production:
    needs: staging
    uses: pellerex-platform/workflows/.github/workflows/cd.yaml@v1
    with:
      project_name: Pellerex.Ecosystem.ManagedApp.RepoUniqueNormalisedIdentifier
      helm_release_name: RepoUniqueIdentifier
      docker_repository: pellerex/RepoUniqueNormalisedIdentifier
      kubernetes_namespace: <production-namespace>
      target_environment: production
    secrets: inherit
